"""MolmoAct2's released FAST action tokenizer and its codec layer,
loaded natively (the tokenizer/codec layer split — see
docs/code-styleguide.md: a TOKENIZER owns the artifact + math, a
CODEC owns the AR conventions around one).

The artifact (``allenai/MolmoAct2-FAST-Tokenizer``) is π's FAST
recipe: orthonormal DCT-II along time, ×``scale`` (10), round,
shift by ``−min_token`` (−55 → +55) clamped at 0, the resulting
symbol string (one ``chr`` per coefficient) through a byte-level BPE.
Decode inverts: BPE → symbol string → ``ord + min_token`` → ÷scale →
inverse DCT. This module reproduces their
``UniversalActionProcessor`` bit-for-bit (pinned by the vendored
reference fixture in tests/fixtures/molmoact2_fast_tokenizer —
encode bins and decode outputs generated by executing their released
code) without the scipy dependency: :func:`bijou.fast.tokenizer.dct_matrix`
is scipy's ``dct(norm="ortho")`` analytically.

Measured release-artifact facts this module must not paper over:

- The trunk's action block is 2048 wide (``<action_0..2047>``) but
  the trained BPE contains only **1005** ids — bins ≥ 1005 are
  unreachable by decode. ``symbol_lengths`` is 0 there, so the
  budget-arithmetic grammar mask excludes them for free.
- **Seven symbol values are quantization holes**: ords
  {3, 9, 12, 14, 19, 22, 27} (DCT levels {−52, −46, −43, −41, −36,
  −33, −28}) are silently dropped by the released tokenizer's
  encode/decode. A chunk whose rounded coefficients hit one cannot
  round-trip — their pipeline would decode short and fall back to a
  ZEROS action chunk. This module is loud instead: :meth:`decode`
  raises on any symbol-count mismatch, and callers that need the
  reference's zeros-fallback semantics (the parity harness)
  implement it explicitly at the call site.
- Per-id decode concatenates exactly to the full-stream decode on
  real streams (fixture-asserted), so per-token symbol lengths ARE
  the decode's budget arithmetic — the property the RL grammar mask
  (item (c)) and the GRPO instrument stand on.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt
import torch
from tokenizers import Tokenizer
from torch import Tensor

from .tokenizer import dct_matrix

FloatArray = npt.NDArray[np.float64]

#: Their normalizer's division-by-zero guard (lerobot
#: ``_NormalizationMixin.eps``); substituted where q99 == q01. Moved
#: here from molmoact2_processing 2026-08-14: the q01/q99 maps are
#: codec-layer math (the raw-unit glue), and ``fast`` sits below
#: ``encoders`` in the import DAG — processing re-exports.
_NORM_EPS = 1e-8


@dataclass(frozen=True, slots=True)
class QuantileStats:
    """One feature's q01/q99 rows and the clamped maps between raw units
    and [-1, 1] — the merged-table normalization scheme. The molmoact2
    families hold ONE per checkpoint as their ``action_quantiles`` (the
    raw↔normalized boundary for flow targets, sampled chunks and the
    discrete detokenization); the codec builds one per call from
    explicit rows. float32 like their normalizer casts to.

    Descending pairs (q01 > q99) are legal: a sign-flipped joint
    carries its orientation in the pair order, and the clamps preserve
    it (q01 → −1, q99 → +1 regardless of order).

    Shapes:
    - ``q01``/``q99``: [D] float32
    """

    q01: Tensor
    q99: Tensor

    def __post_init__(self) -> None:
        if self.q01.shape != self.q99.shape or self.q01.ndim != 1:
            raise ValueError(
                f"expected matching 1-D q01/q99, got {self.q01.shape} / {self.q99.shape}",
            )

    def _on(self, device: torch.device) -> QuantileStats:
        return QuantileStats(q01=self.q01.to(device), q99=self.q99.to(device))

    def _check_width(self, value: Tensor, what: str) -> None:
        if value.shape[-1] != self.q01.shape[0]:
            raise ValueError(
                f"{what} width {value.shape[-1]} != the table's "
                f"{self.q01.shape[0]} — wrong rows for this tensor",
            )

    def normalize(self, value: Tensor) -> Tensor:
        """Input-side path: q01/q99 normalize then clamp to [-1, 1]
        (their ``MolmoAct2ClampNormalizedProcessorStep``) — the map
        action targets and prompt state train under.

        Shapes:
        - ``value``: [..., D] raw units
        - returns: [..., D] float32 in [-1, 1]
        """
        self._check_width(value, "normalize input")
        return normalize_q01q99(value, self._on(value.device)).clamp(-1.0, 1.0)

    def denormalize(self, value: Tensor) -> Tensor:
        """Output-side path: clamp the sampled normalized chunk to
        [-1, 1] (their ``MolmoAct2ClampActionProcessorStep``), then
        invert the q01/q99 map back to raw units in fp32 (callers own
        any dtype round-trip).

        Shapes:
        - ``value``: [..., D] sampled normalized chunk
        - returns: [..., D] float32 raw units
        """
        self._check_width(value, "denormalize input")
        clamped = torch.as_tensor(value, dtype=torch.float32).clamp(-1.0, 1.0)
        return unnormalize_q01q99(clamped, self._on(value.device))

    def rows(self, batch_size: int) -> tuple[Tensor, Tensor]:
        """The table in per-row form — the shape the discrete decode
        consumes (every row detokenizes under the ONE table).

        Shapes:
        - returns: ([batch_size, D], [batch_size, D]) float32
        """
        return (
            self.q01.expand(batch_size, -1),
            self.q99.expand(batch_size, -1),
        )


def normalize_q01q99(value: Tensor, stats: QuantileStats) -> Tensor:
    """Their QUANTILES normalization: ``2 * (x - q01) / (q99 - q01) - 1``
    in float32, zero-width quantile ranges replaced by eps.

    Shapes:
    - ``value``: [..., D] raw units
    - returns: [..., D] float32 normalized
    """
    return normalize_q01q99_rows(value, stats.q01, stats.q99)


def unnormalize_q01q99(value: Tensor, stats: QuantileStats) -> Tensor:
    """Inverse map: ``(x + 1) * (q99 - q01) / 2 + q01`` (their op order).

    Shapes:
    - ``value``: [..., D] normalized
    - returns: [..., D] float32 raw units
    """
    return unnormalize_q01q99_rows(value, stats.q01, stats.q99)


def normalize_q01q99_rows(value: Tensor, q01: Tensor, q99: Tensor) -> Tensor:
    """:func:`normalize_q01q99` on explicit row tensors — the same map
    when the rows are not ONE table ([D]) but broadcast against the
    value (the per-dataset flow scheme's [B, 1, D] item rows).

    Shapes:
    - ``value``: [..., D] raw units; ``q01``/``q99`` broadcastable to it
    - returns: [..., D] float32 normalized
    """
    value = torch.as_tensor(value, dtype=torch.float32)
    denom = q99 - q01
    denom = torch.where(denom == 0, torch.tensor(_NORM_EPS, dtype=torch.float32), denom)
    return 2.0 * (value - q01) / denom - 1.0


def unnormalize_q01q99_rows(value: Tensor, q01: Tensor, q99: Tensor) -> Tensor:
    """:func:`unnormalize_q01q99` on explicit row tensors (see
    :func:`normalize_q01q99_rows`).

    Shapes:
    - ``value``: [..., D] normalized; ``q01``/``q99`` broadcastable to it
    - returns: [..., D] float32 raw units
    """
    value = torch.as_tensor(value, dtype=torch.float32)
    denom = q99 - q01
    denom = torch.where(denom == 0, torch.tensor(_NORM_EPS, dtype=torch.float32), denom)
    return (value + 1.0) * denom / 2.0 + q01


class MolmoAct2FastTokenizer:
    """The released OpenFAST artifact behind a bijou-native surface —
    tokenizer layer only: normalized space, bare bin ids, no specials
    (``<action_start>``/``<action_end>`` are TRUNK vocabulary, carried
    by the codec layer above).

    ``block_vocab`` is the trunk block width (2048 — what the
    ``<action_i>`` rows address); ``bpe_vocab`` the trained BPE's
    actual id count (1005 in the release). ``symbol_lengths[i]`` is
    the number of DCT coefficients bin ``i`` expands to under the
    released decode (0 for ids the BPE cannot produce)."""

    def __init__(
        self,
        bpe: Tokenizer,
        *,
        scale: float,
        min_token: int,
        block_vocab: int,
    ) -> None:
        self.bpe = bpe
        self.scale = float(scale)
        self.min_token = int(min_token)
        self.block_vocab = int(block_vocab)
        self.bpe_vocab = int(bpe.get_vocab_size())
        if self.bpe_vocab > self.block_vocab:
            raise ValueError(
                f"BPE vocab {self.bpe_vocab} exceeds the trunk block "
                f"width {self.block_vocab} — wrong artifact pairing",
            )
        lengths = np.zeros(self.block_vocab, dtype=np.int64)
        for token_id in range(self.bpe_vocab):
            lengths[token_id] = len(bpe.decode([token_id]))
        self.symbol_lengths = lengths
        self._dct_cache: dict[int, FloatArray] = {}

    @classmethod
    def load(cls, artifact_dir: str | Path) -> MolmoAct2FastTokenizer:
        """Load from the released artifact layout (``tokenizer.json``
        + ``processor_config.json`` — scale/min_token/vocab_size)."""
        directory = Path(artifact_dir)
        config = json.loads((directory / "processor_config.json").read_text())
        return cls(
            Tokenizer.from_file(str(directory / "tokenizer.json")),
            scale=config["scale"],
            min_token=config["min_token"],
            block_vocab=config["vocab_size"],
        )

    def _matrix(self, n: int) -> FloatArray:
        if n not in self._dct_cache:
            self._dct_cache[n] = dct_matrix(n)
        return self._dct_cache[n]

    def encode(self, chunk: FloatArray) -> list[int]:
        """NORMALIZED action chunk [T, D] → BPE bin ids, their
        ``__call__`` op-for-op: DCT along time (ortho), ×scale,
        ``np.around``, ``max(x − min_token, 0)`` (the reference's
        clamp — coefficients below ``min_token`` saturate), chr-join
        row-major, BPE encode. Symbols at the seven quantization
        holes are silently dropped by the released BPE — exactly as
        the reference drops them; :meth:`decode` is where this
        module gets loud about it."""
        array = np.asarray(chunk, dtype=np.float64)
        if array.ndim != 2:
            raise ValueError(
                f"encode expects one [T, D] chunk, got shape {array.shape}",
            )
        coefficients = self._matrix(array.shape[0]) @ array
        quantized = np.around(coefficients * self.scale)
        shifted = np.maximum(quantized.flatten() - self.min_token, 0).astype(int)
        symbols = "".join(map(chr, shifted))
        return list(self.bpe.encode(symbols).ids)

    def decode(
        self,
        bins: list[int],
        *,
        time_horizon: int,
        action_dim: int,
    ) -> FloatArray:
        """Bin ids → NORMALIZED action chunk [time_horizon,
        action_dim] float64 — the reference decode with the silent
        parts made loud: out-of-BPE bins and symbol-count mismatches
        raise (the reference prints and returns ZEROS; the parity
        harness reimplements that fallback explicitly where it must
        match)."""
        for token_id in bins:
            if not (0 <= int(token_id) < self.bpe_vocab):
                raise ValueError(
                    f"bin {int(token_id)} outside the trained BPE "
                    f"vocabulary [0, {self.bpe_vocab}) — the release "
                    f"trains {self.bpe_vocab} of {self.block_vocab} "
                    "block rows; the reference zero-fallbacks here",
                )
        symbols = self.bpe.decode(list(map(int, bins)))
        expected = time_horizon * action_dim
        if len(symbols) != expected:
            raise ValueError(
                f"decoded {len(symbols)} DCT coefficients, expected "
                f"{expected} ({time_horizon}×{action_dim}) — "
                "non-decodable stream (short/over-long emission, or a "
                "quantization-hole symbol); the reference "
                "zero-fallbacks here",
            )
        coefficients = (
            np.array([ord(ch) for ch in symbols], dtype=np.float64) + self.min_token
        ).reshape(time_horizon, action_dim)
        return self._matrix(time_horizon).T @ (coefficients / self.scale)
