"""MolmoAct2 FAST codec oracles (molmoact2-ar-head-port item (a)),
pure CPU: bijou/molmoact2/fast_codec.py against the RELEASED
artifact, vendored in tests/fixtures/molmoact2_fast_tokenizer.

The parity fixture (parity.npz + parity_bins.json) was generated by
EXECUTING the released ``UniversalActionProcessor`` verbatim (scipy
DCT + transformers tokenizer wrapper) on five seeded chunks — four
smooth cumsum trajectories and one rough one. What these pin:
(1) encode reproduces the reference bins exactly and decode the
reference actions to DCT-implementation noise (our analytic matrix
vs scipy, ~1e-13 per coefficient); (2) the budget-arithmetic
contract — per-id symbol lengths sum to exactly T×D on every
decodable stream, per-id decode concatenates to the full decode, and
bins ≥ the trained BPE's 1005 ids carry length 0; (3) the measured
release quirks stay loud — the seven quantization-hole symbols
(ords {3, 9, 12, 14, 19, 22, 27}) drop at encode and the resulting
short stream RAISES at decode (the reference silently zero-falls-back
there), as do out-of-vocab bins and truncated streams."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from bijou.fast.molmoact2 import MolmoAct2FastTokenizer

FIXTURE = Path(__file__).parent / "fixtures" / "molmoact2_fast_tokenizer"
HOLES = {3, 9, 12, 14, 19, 22, 27}
T, D = 30, 6


def codec() -> MolmoAct2FastTokenizer:
    return MolmoAct2FastTokenizer.load(FIXTURE)


def fixture() -> tuple[np.ndarray, list[list[int]], np.ndarray]:
    data = np.load(FIXTURE / "parity.npz")
    bins = json.loads((FIXTURE / "parity_bins.json").read_text())
    return data["chunks"], bins, data["decoded"]


def test_release_artifact_facts() -> None:
    """The audit numbers the port stands on: 1005 trained BPE ids in
    a 2048-wide block, scale 10, min_token −55."""
    loaded = codec()
    assert (loaded.block_vocab, loaded.bpe_vocab) == (2048, 1005)
    assert (loaded.scale, loaded.min_token) == (10.0, -55)


def test_encode_matches_reference_bins_exactly() -> None:
    loaded = codec()
    chunks, bins, _ = fixture()
    for chunk, reference in zip(chunks, bins, strict=True):
        assert loaded.encode(chunk) == reference


def test_decode_matches_reference_actions() -> None:
    """Bit-parity up to DCT implementation noise: the analytic
    orthonormal matrix vs scipy's FFT-based transform."""
    loaded = codec()
    _, bins, decoded = fixture()
    for reference_bins, reference_actions in zip(bins, decoded, strict=True):
        ours = loaded.decode(reference_bins, time_horizon=T, action_dim=D)
        assert np.abs(ours - reference_actions).max() < 1e-9


def test_roundtrip_error_is_quantization_bounded() -> None:
    loaded = codec()
    chunks, bins, _ = fixture()
    for chunk, stream in zip(chunks, bins, strict=True):
        out = loaded.decode(stream, time_horizon=T, action_dim=D)
        assert np.abs(out - chunk).max() < 0.15


def test_symbol_lengths_are_the_budget_arithmetic() -> None:
    """Per-id lengths sum to exactly T×D on every decodable stream,
    per-id decode concatenates to the full decode (the property the
    RL grammar mask stands on), untrained bins carry length 0, and
    every trained bin expands to ≥1 symbol."""
    loaded = codec()
    _, bins, _ = fixture()
    lengths = loaded.symbol_lengths
    assert lengths.shape == (2048,)
    assert (lengths[1005:] == 0).all()
    assert (lengths[:1005] >= 1).all()
    for stream in bins:
        assert int(lengths[stream].sum()) == T * D
        concat = "".join(loaded.bpe.decode([i]) for i in stream)
        assert concat == loaded.bpe.decode(stream)


def test_quantization_holes_are_loud() -> None:
    """A chunk whose rounded DCT coefficient lands on a hole symbol
    loses it at encode (the released artifact's behavior); decoding
    the short stream must RAISE, never silently zero-fallback."""
    loaded = codec()
    hole_level = (min(HOLES) + loaded.min_token) / loaded.scale  # −5.2
    chunk = np.zeros((T, D))
    # First DCT coefficient of dimension 0 ≈ mean × sqrt(T): steer it
    # onto the hole level exactly.
    chunk[:, 0] = hole_level / np.sqrt(T)
    stream = loaded.encode(chunk)
    assert int(loaded.symbol_lengths[stream].sum()) == T * D - 1
    with pytest.raises(ValueError, match=r"quantization-hole|non-decodable"):
        loaded.decode(stream, time_horizon=T, action_dim=D)


def test_guards_are_loud() -> None:
    loaded = codec()
    _, bins, _ = fixture()
    with pytest.raises(ValueError, match="outside the trained BPE"):
        loaded.decode([1500], time_horizon=T, action_dim=D)
    with pytest.raises(ValueError, match="expected 180"):
        loaded.decode(bins[0][:-1], time_horizon=T, action_dim=D)
    with pytest.raises(ValueError, match="one \\[T, D\\] chunk"):
        loaded.encode(np.zeros((2, T, D)))
