"""MolmoAct2 FAST codec oracles (molmoact2-ar-head-port item (a)),
pure CPU: bijou/molmoact2/fast_codec.py against the RELEASED
artifact, vendored in tests/fixtures/molmoact2_fast_tokenizer.

The parity fixture (parity.npz + parity_bins.json) was generated by
EXECUTING the released ``UniversalActionProcessor`` verbatim (scipy
DCT + transformers tokenizer wrapper) on five seeded chunks — four
smooth cumsum trajectories and one rough one. What these pin:
(1) encode reproduces the reference bins exactly and decode the
reference actions to DCT-implementation noise (our analytic matrix
vs scipy, ~1e-13 per coefficient); (2) the budget-arithmetic
contract — per-id symbol lengths sum to exactly T×D on every
decodable stream, per-id decode concatenates to the full decode, and
bins ≥ the trained BPE's 1005 ids carry length 0; (3) the measured
release quirks stay loud — the seven quantization-hole symbols
(ords {3, 9, 12, 14, 19, 22, 27}) drop at encode and the resulting
short stream RAISES at decode (the reference silently zero-falls-back
there), as do out-of-vocab bins and truncated streams."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
import torch

from bijou.fast.molmoact2 import (
    MolmoAct2FastTokenizer,
    QuantileStats,
    unnormalize_action,
)
from bijou.modelling.codecs import ActionCodec, FastActionCodec, MolmoAct2ActionCodec

FIXTURE = Path(__file__).parent / "fixtures" / "molmoact2_fast_tokenizer"
HOLES = {3, 9, 12, 14, 19, 22, 27}
T, D = 30, 6


def codec() -> MolmoAct2FastTokenizer:
    return MolmoAct2FastTokenizer.load(FIXTURE)


def fixture() -> tuple[np.ndarray, list[list[int]], np.ndarray]:
    data = np.load(FIXTURE / "parity.npz")
    bins = json.loads((FIXTURE / "parity_bins.json").read_text())
    return data["chunks"], bins, data["decoded"]


def test_release_artifact_facts() -> None:
    """The audit numbers the port stands on: 1005 trained BPE ids in
    a 2048-wide block, scale 10, min_token −55."""
    loaded = codec()
    assert (loaded.block_vocab, loaded.bpe_vocab) == (2048, 1005)
    assert (loaded.scale, loaded.min_token) == (10.0, -55)


def test_encode_matches_reference_bins_exactly() -> None:
    loaded = codec()
    chunks, bins, _ = fixture()
    for chunk, reference in zip(chunks, bins, strict=True):
        assert loaded.encode(chunk) == reference


def test_decode_matches_reference_actions() -> None:
    """Bit-parity up to DCT implementation noise: the analytic
    orthonormal matrix vs scipy's FFT-based transform."""
    loaded = codec()
    _, bins, decoded = fixture()
    for reference_bins, reference_actions in zip(bins, decoded, strict=True):
        ours = loaded.decode(reference_bins, time_horizon=T, action_dim=D)
        assert np.abs(ours - reference_actions).max() < 1e-9


def test_roundtrip_error_is_quantization_bounded() -> None:
    loaded = codec()
    chunks, bins, _ = fixture()
    for chunk, stream in zip(chunks, bins, strict=True):
        out = loaded.decode(stream, time_horizon=T, action_dim=D)
        assert np.abs(out - chunk).max() < 0.15


def test_symbol_lengths_are_the_budget_arithmetic() -> None:
    """Per-id lengths sum to exactly T×D on every decodable stream,
    per-id decode concatenates to the full decode (the property the
    RL grammar mask stands on), untrained bins carry length 0, and
    every trained bin expands to ≥1 symbol."""
    loaded = codec()
    _, bins, _ = fixture()
    lengths = loaded.symbol_lengths
    assert lengths.shape == (2048,)
    assert (lengths[1005:] == 0).all()
    assert (lengths[:1005] >= 1).all()
    for stream in bins:
        assert int(lengths[stream].sum()) == T * D
        concat = "".join(loaded.bpe.decode([i]) for i in stream)
        assert concat == loaded.bpe.decode(stream)


def test_quantization_holes_are_loud() -> None:
    """A chunk whose rounded DCT coefficient lands on a hole symbol
    loses it at encode (the released artifact's behavior); decoding
    the short stream must RAISE, never silently zero-fallback."""
    loaded = codec()
    hole_level = (min(HOLES) + loaded.min_token) / loaded.scale  # −5.2
    chunk = np.zeros((T, D))
    # First DCT coefficient of dimension 0 ≈ mean × sqrt(T): steer it
    # onto the hole level exactly.
    chunk[:, 0] = hole_level / np.sqrt(T)
    stream = loaded.encode(chunk)
    assert int(loaded.symbol_lengths[stream].sum()) == T * D - 1
    with pytest.raises(ValueError, match=r"quantization-hole|non-decodable"):
        loaded.decode(stream, time_horizon=T, action_dim=D)


def test_guards_are_loud() -> None:
    loaded = codec()
    _, bins, _ = fixture()
    with pytest.raises(ValueError, match="outside the trained BPE"):
        loaded.decode([1500], time_horizon=T, action_dim=D)
    with pytest.raises(ValueError, match="expected 180"):
        loaded.decode(bins[0][:-1], time_horizon=T, action_dim=D)
    with pytest.raises(ValueError, match="one \\[T, D\\] chunk"):
        loaded.encode(np.zeros((2, T, D)))


# --- MolmoAct2ActionCodec (the codec layer over the released artifact) ---

TINY_FAST_FIXTURE = Path(__file__).parent / "fixtures" / "tiny_fast_tokenizer"

# Identity-class quantile rows (q01 = −1, q99 = 1 ⇒ denom = 2): the
# affine maps reduce to (x + 1) − 1, so raw ≈ normalized and the
# fixture's NORMALIZED chunks can drive raw-unit surfaces. Each test
# asserts the round-trip precondition it relies on.
Q01 = np.full(D, -1.0)
Q99 = np.full(D, 1.0)
# A deliberately non-trivial table for op-order tests (bitwise
# comparisons against the inline reference recipe — same ops, any
# values).
Q01_RIG = np.array([-92.3, -104.1, -3.7, -88.0, -45.5, 2.1])
Q99_RIG = np.array([88.9, 102.6, 178.2, 91.4, 47.0, 97.3])


def adapter() -> MolmoAct2ActionCodec:
    return MolmoAct2ActionCodec(codec(), time_horizon=T, action_dim=D)


def test_protocol_conformance_and_id_space() -> None:
    """Both families satisfy the ActionCodec Protocol (the annotations
    make pyright prove it), and the released family's id-space facts
    hold: bare 2048 block, specials at NEGATIVE offsets — block_base +
    boa/pad = <action_start>/<action_end> (151932/3 for release
    block_base 151934) with zero ±2 rebase of the bins."""
    released: ActionCodec = adapter()
    fitted: ActionCodec = FastActionCodec.load(TINY_FAST_FIXTURE)
    assert (released.boa, released.pad) == (-2, -1)
    assert released.vocab_total == 2048
    assert (released.time_horizon, released.action_dim) == (T, D)
    assert released.symbol_lengths.shape == (2048,)
    assert (released.symbol_lengths == codec().symbol_lengths).all()
    # Our fitted family keeps specials INSIDE the block, after the body.
    assert fitted.boa == fitted.vocab_total - 2
    assert fitted.pad == fitted.vocab_total - 1


def test_adapter_encode_prepends_boa_and_matches_reference_bins() -> None:
    """Raw-unit encode = [boa, *reference bins] under the identity-class
    table (round-trip exactness asserted as a precondition — if a
    machine ever drifts a coefficient onto a rounding boundary, this
    names the mechanism instead of flaking)."""
    loaded = adapter()
    chunks, bins, _ = fixture()
    stats = QuantileStats(
        q01=torch.tensor(Q01, dtype=torch.float32),
        q99=torch.tensor(Q99, dtype=torch.float32),
    )
    for chunk, reference in zip(chunks, bins, strict=True):
        raw = unnormalize_action(torch.from_numpy(chunk), stats).double().numpy()
        renormalized = (
            2.0 * (torch.from_numpy(raw).float() - stats.q01) / (stats.q99 - stats.q01)
        ) - 1.0
        np.testing.assert_allclose(
            renormalized.double().numpy(),
            chunk,
            atol=5e-7,
            err_msg="identity-table round-trip drifted — re-baseline the test",
        )
        assert loaded.encode(raw, Q01, Q99) == [-2, *reference]


def test_adapter_decode_is_the_reference_tail_bitwise() -> None:
    """decode = their output tail op-for-op: fp64 DCT decode → fp32 →
    clamp [−1, 1] → q01/q99 inversion (torch fp32) — BITWISE equal to
    the inline recipe, returned as fp64-of-fp32 so a downstream
    ``.float()`` recovers the exact executed bytes. A leading boa
    strips; the pad offset inside a body raises."""
    loaded = adapter()
    raw_tokenizer = codec()
    _, bins, _ = fixture()
    stats = QuantileStats(
        q01=torch.tensor(Q01_RIG, dtype=torch.float32),
        q99=torch.tensor(Q99_RIG, dtype=torch.float32),
    )
    for stream in bins:
        expected = (
            unnormalize_action(
                torch.from_numpy(
                    raw_tokenizer.decode(stream, time_horizon=T, action_dim=D),
                ).to(torch.float32),
                stats,
            )
            .double()
            .numpy()
        )
        ours = loaded.decode(stream, Q01_RIG, Q99_RIG)
        assert np.array_equal(ours, expected)
        assert np.array_equal(loaded.decode([-2, *stream], Q01_RIG, Q99_RIG), expected)
        fp32_roundtrip = ours.astype(np.float32).astype(np.float64)
        assert np.array_equal(fp32_roundtrip, ours)  # fp64-of-fp32 contract
    with pytest.raises(ValueError, match="pad offset"):
        loaded.decode([-1, *bins[0]], Q01_RIG, Q99_RIG)


def test_adapter_encode_refuses_quantization_hole_chunks() -> None:
    """The encode-side totality guard: a chunk that hits a released-BPE
    hole would silently shorten a CE target — the codec refuses it by
    symbol-budget arithmetic instead."""
    loaded = adapter()
    hole_level = (min(HOLES) + codec().min_token) / codec().scale  # −5.2
    normalized = np.zeros((T, D))
    normalized[:, 0] = hole_level / np.sqrt(T)
    stats = QuantileStats(
        q01=torch.tensor(Q01, dtype=torch.float32),
        q99=torch.tensor(Q99, dtype=torch.float32),
    )
    raw = unnormalize_action(torch.from_numpy(normalized), stats).double().numpy()
    with pytest.raises(ValueError, match="quantization hole"):
        loaded.encode(raw, Q01, Q99)


def test_adapter_geometry_guards() -> None:
    with pytest.raises(ValueError, match="geometry must be positive"):
        MolmoAct2ActionCodec(codec(), time_horizon=0, action_dim=D)
    with pytest.raises(ValueError, match=r"encode expects \[30, 6\]"):
        adapter().encode(np.zeros((T, D + 1)), Q01, Q99)
