"""MolmoAct2's released FAST action tokenizer, loaded natively — the
AR-head port's codec half (queue: molmoact2-ar-head-port item (a),
owner steering 2026-08-13 10:02Z).

The artifact (``allenai/MolmoAct2-FAST-Tokenizer``) is π's FAST
recipe: orthonormal DCT-II along time, ×``scale`` (10), round,
shift by ``−min_token`` (−55 → +55) clamped at 0, the resulting
symbol string (one ``chr`` per coefficient) through a byte-level BPE.
Decode inverts: BPE → symbol string → ``ord + min_token`` → ÷scale →
inverse DCT. This module reproduces their
``UniversalActionProcessor`` bit-for-bit (pinned by the vendored
reference fixture in tests/fixtures/molmoact2_fast_tokenizer —
encode bins and decode outputs generated by executing their released
code) without the scipy dependency: :func:`bijou.fast.tokenizer.dct_matrix`
is scipy's ``dct(norm="ortho")`` analytically.

Measured release-artifact facts the port must not paper over
(audit 2026-08-13, in-channel):

- The trunk's action block is 2048 wide (``<action_0..2047>``) but
  the trained BPE contains only **1005** ids — bins ≥ 1005 are
  unreachable by decode. ``symbol_lengths`` is 0 there, so the
  budget-arithmetic grammar mask excludes them for free.
- **Seven symbol values are quantization holes**: ords
  {3, 9, 12, 14, 19, 22, 27} (DCT levels {−52, −46, −43, −41, −36,
  −33, −28}) are silently dropped by the released tokenizer's
  encode/decode. A chunk whose rounded coefficients hit one cannot
  round-trip — their pipeline would decode short and fall back to a
  ZEROS action chunk. This module is loud instead: :meth:`decode`
  raises on any symbol-count mismatch, and callers that need the
  reference's zeros-fallback semantics (the parity harness)
  implement it explicitly at the call site.
- Per-id decode concatenates exactly to the full-stream decode on
  real streams (fixture-asserted), so per-token symbol lengths ARE
  the decode's budget arithmetic — the property the RL grammar mask
  (item (c)) and the GRPO instrument stand on.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import numpy.typing as npt
from tokenizers import Tokenizer

from ..fast.tokenizer import dct_matrix

FloatArray = npt.NDArray[np.float64]


class MolmoAct2FastCodec:
    """The released OpenFAST artifact behind a bijou-native surface.

    ``block_vocab`` is the trunk block width (2048 — what the
    ``<action_i>`` rows address); ``bpe_vocab`` the trained BPE's
    actual id count (1005 in the release). ``symbol_lengths[i]`` is
    the number of DCT coefficients bin ``i`` expands to under the
    released decode (0 for ids the BPE cannot produce)."""

    def __init__(
        self,
        bpe: Tokenizer,
        *,
        scale: float,
        min_token: int,
        block_vocab: int,
    ) -> None:
        self.bpe = bpe
        self.scale = float(scale)
        self.min_token = int(min_token)
        self.block_vocab = int(block_vocab)
        self.bpe_vocab = int(bpe.get_vocab_size())
        if self.bpe_vocab > self.block_vocab:
            raise ValueError(
                f"BPE vocab {self.bpe_vocab} exceeds the trunk block "
                f"width {self.block_vocab} — wrong artifact pairing",
            )
        lengths = np.zeros(self.block_vocab, dtype=np.int64)
        for token_id in range(self.bpe_vocab):
            lengths[token_id] = len(bpe.decode([token_id]))
        self.symbol_lengths = lengths
        self._dct_cache: dict[int, FloatArray] = {}

    @classmethod
    def load(cls, artifact_dir: str | Path) -> MolmoAct2FastCodec:
        """Load from the released artifact layout (``tokenizer.json``
        + ``processor_config.json`` — scale/min_token/vocab_size)."""
        directory = Path(artifact_dir)
        config = json.loads((directory / "processor_config.json").read_text())
        return cls(
            Tokenizer.from_file(str(directory / "tokenizer.json")),
            scale=config["scale"],
            min_token=config["min_token"],
            block_vocab=config["vocab_size"],
        )

    def _matrix(self, n: int) -> FloatArray:
        if n not in self._dct_cache:
            self._dct_cache[n] = dct_matrix(n)
        return self._dct_cache[n]

    def encode(self, chunk: FloatArray) -> list[int]:
        """NORMALIZED action chunk [T, D] → BPE bin ids, their
        ``__call__`` op-for-op: DCT along time (ortho), ×scale,
        ``np.around``, ``max(x − min_token, 0)`` (the reference's
        clamp — coefficients below ``min_token`` saturate), chr-join
        row-major, BPE encode. Symbols at the seven quantization
        holes are silently dropped by the released BPE — exactly as
        the reference drops them; :meth:`decode` is where this
        module gets loud about it."""
        array = np.asarray(chunk, dtype=np.float64)
        if array.ndim != 2:
            raise ValueError(
                f"encode expects one [T, D] chunk, got shape {array.shape}",
            )
        coefficients = self._matrix(array.shape[0]) @ array
        quantized = np.around(coefficients * self.scale)
        shifted = np.maximum(quantized.flatten() - self.min_token, 0).astype(int)
        symbols = "".join(map(chr, shifted))
        return list(self.bpe.encode(symbols).ids)

    def decode(
        self,
        bins: list[int],
        *,
        time_horizon: int,
        action_dim: int,
    ) -> FloatArray:
        """Bin ids → NORMALIZED action chunk [time_horizon,
        action_dim] float64 — the reference decode with the silent
        parts made loud: out-of-BPE bins and symbol-count mismatches
        raise (the reference prints and returns ZEROS; the parity
        harness reimplements that fallback explicitly where it must
        match)."""
        for token_id in bins:
            if not (0 <= int(token_id) < self.bpe_vocab):
                raise ValueError(
                    f"bin {int(token_id)} outside the trained BPE "
                    f"vocabulary [0, {self.bpe_vocab}) — the release "
                    f"trains {self.bpe_vocab} of {self.block_vocab} "
                    "block rows; the reference zero-fallbacks here",
                )
        symbols = self.bpe.decode(list(map(int, bins)))
        expected = time_horizon * action_dim
        if len(symbols) != expected:
            raise ValueError(
                f"decoded {len(symbols)} DCT coefficients, expected "
                f"{expected} ({time_horizon}×{action_dim}) — "
                "non-decodable stream (short/over-long emission, or a "
                "quantization-hole symbol); the reference "
                "zero-fallbacks here",
            )
        coefficients = (
            np.array([ord(ch) for ch in symbols], dtype=np.float64) + self.min_token
        ).reshape(time_horizon, action_dim)
        return self._matrix(time_horizon).T @ (coefficients / self.scale)
