"""Re-export shim — the MolmoAct2 leaf transforms moved to the
first-class encoder side (`bijou/encoders/molmoact2_processing.py`,
phase 1 of docs/molmoact2-retirement.md). This shim keeps the port
package's call sites byte-compatible until the package retires
(phase 5), exactly the judge/schema re-export precedent: moved names,
same import paths, no behavior change.
"""

from __future__ import annotations

from ..encoders.molmoact2_processing import (
    ACTION_OUTPUT_ID,
    BOS_ID,
    IM_END_ID,
    IM_PATCH_ID,
    IM_START_ID,
    IMAGE_TOKEN_STRINGS,
    PAD_ID,
    RESIZE_GRID,
    STATE_TOKEN_0_ID,
    SUPPORTED_ACTION_MODES,
    PackedActionExample,
    QuantileStats,
    build_robot_prompt,
    discrete_state_string,
    encode_action_prompt,
    encoder_attention_mask,
    image_token_ids_resize,
    infer_max_sequence_length,
    load_norm_stats,
    normalize_q01q99,
    normalize_state,
    normalize_task_text,
    pack_action_example,
    process_image_resize,
    require_single_obs,
    to_uint8_rgb,
    unnormalize_action,
    unnormalize_q01q99,
)

__all__ = [
    "ACTION_OUTPUT_ID",
    "BOS_ID",
    "IMAGE_TOKEN_STRINGS",
    "IM_END_ID",
    "IM_PATCH_ID",
    "IM_START_ID",
    "PAD_ID",
    "RESIZE_GRID",
    "STATE_TOKEN_0_ID",
    "SUPPORTED_ACTION_MODES",
    "PackedActionExample",
    "QuantileStats",
    "build_robot_prompt",
    "discrete_state_string",
    "encode_action_prompt",
    "encoder_attention_mask",
    "image_token_ids_resize",
    "infer_max_sequence_length",
    "load_norm_stats",
    "normalize_q01q99",
    "normalize_state",
    "normalize_task_text",
    "pack_action_example",
    "process_image_resize",
    "require_single_obs",
    "to_uint8_rgb",
    "unnormalize_action",
    "unnormalize_q01q99",
]
